name: Build and Push Backend Image

description: Build and push Docker image using Buildx

inputs:
  registry:
    description: Container registry (e.g., ghcr.io or docker.io)
    required: false
    default: docker.io
  username:
    description: Registry username or actor
    required: true
  password:
    description: Registry password or token
    required: true
  image_name:
    description: Full image name without tag (e.g., ghcr.io/owner/repo)
    required: true
  context:
    description: Build context
    required: false
    default: .
  dockerfile:
    description: Path to Dockerfile
    required: false
    default: Dockerfile
  platforms:
    description: Target platforms (e.g., linux/amd64,linux/arm64)
    required: false
    default: linux/amd64
  tags:
    description: Single tag string (e.g., latest)
    required: false
    default: latest
  build_args:
    description: Optional build args (newline or comma separated)
    required: false
  tags_full:
    description: Full image tags (newline-separated)
    required: false

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Compute tags
      id: compute
      shell: bash
      run: |
        TAGS="${{ inputs.tags_full }}"
        if [ -z "$TAGS" ]; then
          TAGS="${{ inputs.image_name }}:${{ inputs.tags }}"
        fi
        {
          echo "tags<<EOF"
          echo -e "$TAGS"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ steps.compute.outputs.tags }}
        build-args: ${{ inputs.build_args }}