name: Build and Push Backend Image

description: Build and push backend Docker image to GHCR

inputs:
  ghcr_username:
    description: GitHub username for GHCR login
    required: true
  github_token:
    description: GitHub token for GHCR login (GITHUB_TOKEN)
    required: true
  context:
    description: Docker build context
    required: false
    default: ./
  file:
    description: Dockerfile path
    required: false
    default: Dockerfile
  platforms:
    description: Target platforms
    required: false
    default: linux/amd64
  tags:
    description: Image tags (newline-separated)
    required: true

outputs:
  digest:
    description: Image digest
    value: ${{ steps.build.outputs.digest }}

runs:
  using: composite
  steps:
    - name: Checkout (needed for actions using repo files)
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr_username }}
        password: ${{ inputs.github_token }}

    - name: Compute image tags
      id: meta
      shell: bash
      run: |
        BASE="ghcr.io/${{ github.repository_owner }}/store-vendure-backend"
        TAGS="${BASE}:${{ github.sha }}"
        if [ "${{ github.ref_type }}" = "branch" ]; then
          TAGS="${TAGS}\n${BASE}:${{ github.ref_name }}"
          if [ "${{ github.ref_name }}" = "deploy" ]; then
            TAGS="${TAGS}\n${BASE}:deploy-latest"
          fi
        elif [ "${{ github.ref_type }}" = "tag" ]; then
          TAGS="${TAGS}\n${BASE}:${{ github.ref_name }}"
        fi
        {
          echo "tags<<EOF"
          echo -e "${TAGS}"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}